language: c
matrix:
  include:
    - compiler: clang
      os: osx
      env: ARCH=native
    - compiler: gcc
      os: osx
      env: ARCH=native
    - compiler: clang
      os: linux
      env: ARCH=native
      dist: bionic
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=native
      dist: bionic
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=mingw32
      dist: bionic
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=mingw64
      dist: bionic
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=arm32
      dist: bionic
      sudo: required
    - compiler: gcc
      os: linux
      env: ARCH=arm64
      dist: bionic
      sudo: required
    - language: android
      name: "Android 8.x 9"
      env: ARCH=android MIN_NAL=26 MAX_NAL=28
      dist: trusty
      sudo: required
      android:
        components:
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository
    - language: android
      name: "Android 10 11"
      env: ARCH=android MIN_NAL=29 MAX_NAL=30
      dist: trusty
      sudo: required
      android:
        components:
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository

script:
  "./scripts/travis"

after_failure:
  "./scripts/travis_failure"
