name: Fedora/Rawhide

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_and_test:
    strategy:
      matrix:
        cc: [ gcc, clang ]
    name: ${{ matrix.cc }}
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'libressl' || github.event_name != 'schedule' }}
    container:
      image: fedora:rawhide
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Install dependencies
      run: |
        dnf -y install git make clang cmake ninja-build autoconf automake libtool diffutils patch gawk
    - name: Pull upstream source
      run: |
        ./update.sh
    - name: Build
      run: |
         CC=${{ matrix.cc }} cmake -GNinja -DBUILD_SHARED_LIBS=ON .
         ninja
    - name: Test
      run: |
         ninja test
