# GitHub Actions workflow to create releases from tags.
name: "Release"

on:
  push:
    tags: [ "v*" ]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-24.04"
    outputs:
      upload_url: "${{ steps.create_release.outputs.upload_url }}"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Generate version changelog"
        run: .github/scripts/changelog.sh "$VERSION" > release-changelog.txt
        env:
          VERSION: "${{ github.ref_name }}"

      - name: "Create GitHub release"
        id: create_release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          body_path: "${{ github.workspace }}/release-changelog.txt"

  build-windows:
    name: "${{ matrix.os }}/${{ matrix.arch }}"
    runs-on: "${{ matrix.os }}"
    needs: ["release"]
    strategy:
      matrix:
        os: [ "windows-2022" ]
        arch: [ "Win32", "x64", "ARM64" ]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda # v2.30.0
        with:
          update: true
          install: >-
            autoconf
            automake
            diffutils
            libtool
            gcc
            git
            patch
            perl

      - shell: msys2 {0}
        run: ./autogen.sh

      - shell: cmd
        run: cmake -Bbuild -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_INSTALL_PREFIX=local

      - shell: cmd
        run: cmake --build build --config Release

      - shell: cmd
        run: cmake --install build --config Release

      - shell: pwsh
        run: Compress-Archive -Path local\* "libressl_${{ github.ref_name }}_windows_${{ matrix.arch }}.zip"

      - name: "Upload release artifact"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            libressl_${{ github.ref_name }}_windows_${{ matrix.arch }}.zip
