name: solaris_ci

on:
  workflow_dispatch:

jobs:
  build-native:
    strategy:
      matrix:
        release: [11.4]
    runs-on: ubuntu-latest
    continue-on-error: false
    name: Solaris ${{ matrix.release }}
    steps:
    - name: Checkout source
      uses: actions/checkout@main
    - name: Configure source
      run: |
        brew install automake autoconf libtool
        ./autogen.sh
    - name: Build on VM
      uses: vmactions/solaris-vm@v1
      with:
        prepare: |
          pkg install gcc make
        run: |
          MAKE=gmake ./configure
          gmake -j2 check || (cat tests/test-suite.log && exit 1)
